# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainclone', '0003_auto_20180724_0813'),
    ]

    operations = [
    ]
