# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainclone', '0007_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Name',
            field=models.TextField(default='Anonymous'),
        ),
    ]
